export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";


export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODCUTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST"

export const FETCH_PRODCUTS_CATEGORY_FAILURE = "FETCH_PRODUCTS_CATEGORY_FAILURE"
export const FETCH_PRODUCTS_CATEGORY_SUCCESS = "FETCH_PRODUCTS_CATEGORY_SUCCESS"

 export const FETCH_PRODUCTS_BY_CATEGORY_REQUEST = "FETCH_PRODUCTS_CATEGORY_REQUEST"
 export const FETCH_FLASH_SALES_REQUEST = "FETCH_FLASH_SALES_REQUEST"
 export const FETCH_FLASH_SALES_SUCCESS = "FETCH_FLASH_SALES_SUCCESS"
 export const  FETCH_FLASH_SALES_FAILURE = "FETCH_FLASH_SALES_FAILURE"